version: '3.8'

services:
  mysql:
    image: arm64v8/mysql:8.0.29
    container_name: 'ql-mysql'
    hostname: 'ql-mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - quarkus-learning:/var/lib/data:delegated
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - quarkus-learning
    ports:
      - ${MYSQL_PORT}:3306
    command: --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone="UTC"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped

volumes:
  quarkus-learning:
    name: quarkus-learning
    driver: local

networks:
  quarkus-learning:
    name: ql
    driver: bridge